#!/usr/bin/bash

#set glob to read hidden files
shopt -s dotglob

checkDir()
{
if ls -1qA | grep -q .; then
    :
else
    return
fi

for file in *; do
    if echo $file | grep -Eq '^\-|^\.|[^A-Za-z_\.\-]|^.{15,}$'; then
	if [ -d "$file" ]; then
	    echo `pwd`/$file/
	else
	    echo `pwd`/$file
	fi
	
    fi
    REPEATS=`find . -maxdepth 1 -iname "$file" | wc -l`
    if test $REPEATS -gt 1; then
	if [ -d "$file" ]; then
	    echo `pwd`/$file/
	else
	    echo `pwd`/$file
	fi
    fi
done
}

DIR=$1

#ensure input DIR is valid
if [ "$#" -gt 1 ]; then
    >&2 echo "too many arguments"
    exit 1
elif echo | grep -Eq '^\-'; then
    >&2 echo "input directory cannot start with dash"
    exit 1
elif [ -z "$DIR" ]
then
    DIR="."
elif [ ! -d "$DIR" ]
then
    >&2 echo "$DIR is not a directory"
    exit 1
elif [ ! -r "$DIR" ]
then
    >&2 echo "read permissions not enabled on $DIR"
    exit 0
fi

cd $DIR
checkDir
